apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: sk-rohit-portfolio-service
spec:
  selector:
    app: sk-rohit-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
